backend:
  url: "http://api:8000"
llm:
  # LLM Provider ("groq", "openai", or "azure_openai")
  vendor: "groq"
  model: "openai/gpt-oss-20b"
  temperature: 0

openai:
# OpenAI-specific configuration parameters (non-secret)
  openai_base_url: "https://api.gpt.medtronic.com/providers/openai/v1"

# Azure OpenAI-specific configuration parameters (non-secret)
azure:
  deployment_name: "gpt-5-mini"
  api_version: "2024-08-01-preview"
  azure_endpoint: "https://aiailzpoceusg5cy.services.ai.azure.com"


email_agent:
  # every second of real time is treated as 1 hour of virtual time
  virtual_speedup_factor: 3600.0