[project]
name = "aihub-mod-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.139.0",
    "jupyter>=1.0.0",
    "kagglehub>=1.0.2",
    "langchain>=1.3.10",
    "langchain-anthropic>=1.4.6",
    "langchain-community>=0.4.2",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.0.0",
    "langgraph>=1.0.0",
    "langgraph-checkpoint-postgres>=3.1.0",
    "langgraph-checkpoint-sqlite>=3.1.0",
    "langgraph-cli[inmem]>=0.4.0",
    "pandas>=3.0.3",
    "psycopg-pool>=3.3.1",
    "pydantic>=2.13.4",
    "pygraphviz>=2.0.1",
    "pyyaml>=6.0.3",
    "streamlit>=1.59.1",
]
