backend:
  url: "http://api:8000"
llm:
  # LLM Provider ("groq", "openai", or "azure_openai")
  vendor: "groq"
  model: "llama-3.3-70b-versatile"
  temperature: 0

openai:
# OpenAI-specific configuration parameters (non-secret)
  openai_base_url: "https://your-openai-base-url.com"

# Azure OpenAI-specific configuration parameters (non-secret)
azure:
  deployment_name: "your_deployment_name_here"
  api_version: "2023-06-01-preview"
  azure_endpoint: "https://your-resource-name.openai.azure.com/"


email_agent:
  # every second of real time is treated as 1 hour of virtual time
  virtual_speedup_factor: 3600.0
